Look for broker-node in $PATH
Instead of hardcoding the binary, we let the user choose their location
of broker-node by adjusting $PATH accordingly.

diff --git a/brocon18/evaluation/latency/benchmark b/brocon18/evaluation/latency/benchmark
--- a/brocon18/evaluation/latency/benchmark
+++ b/brocon18/evaluation/latency/benchmark
@@ -5,7 +5,7 @@ function launch_ping() {
   num_relays=$2
   for payload in 0 1 10 100 1000 10000 100000 1000000 10000000 100000000; do
     echo "start ping for $num_relays relays with payload $payload connecting to peer $peer"
-    out=$($broker_node ${verbose:+'-v'} -N "ping" -p "[<tcp://[::1]:$peer>]" -t foobar -m "'ping'" -n ${iterations} -s $payload)
+    out=$(broker-node ${verbose:+'-v'} -N "ping" -p "[<tcp://[::1]:$peer>]" -t foobar -m "'ping'" -n ${iterations} -s $payload)
     while read -r line; do
       echo "$num_relays,$payload,$line" >> latency.csv
     done <<< "$out"
@@ -16,13 +16,13 @@ function launch_relay() {
   listen=$1
   peer=$2
   echo "start relay ${listen} <-> ${peer}" 1>&2
-  $broker_node -N "relay_${listen}" ${verbose:+'-v'} -l ${listen} -t foobar -m "'relay'" -p "[<tcp://[::1]:${peer}>]" &
+  broker-node -N "relay_${listen}" ${verbose:+'-v'} -l ${listen} -t foobar -m "'relay'" -p "[<tcp://[::1]:${peer}>]" &
 }
 
 function launch_pong() {
   listen=$1
   echo "start pong at port ${listen}" 1>&2
-  $broker_node -N "pong" ${verbose:+'-v'} -l ${listen} -t foobar -m "'pong'" & 2> pong.log
+  broker-node -N "pong" ${verbose:+'-v'} -l ${listen} -t foobar -m "'pong'" & 2> pong.log
 }
 
 function run_test() {
@@ -44,11 +44,9 @@ USAGE="usage: $0 [options] <min-num-relays> <max-num-relays>"
 
 unset verbose
 unset help_
-broker_node=../../broker/build/bin/broker-node
 append=false
 port=4001
 iterations=100
-ret=0
 while getopts "n:p:ahv" flag; do
 case "$flag" in
     n) iterations=$OPTARG;;
@@ -56,14 +54,19 @@ case "$flag" in
     a) append=true;;
     h) help_=true;;
     v) verbose=true;;
-    \?) help_=true; ret=1;;
+    \?) help_=true;;
 esac
 done
 shift $((OPTIND-1))
 
 if [ "$help_" = true ] || [ "$#" -lt 2 ]; then
   echo $USAGE
-  exit $ret;
+  exit 1
+fi
+
+if ! which broker-node > /dev/null 2>&1; then
+  echo 'broker-node not found in $PATH'
+  exit 1
 fi
 
 if [ "$append" = false ]; then
@@ -75,4 +78,4 @@ for i in $(seq $1 $2); do
   run_test $i
 done
 
-exit $ret
+exit 0
